### ISSUE TITLE
Feature Request: QR-Codes for Rooms

### ISSUE THREAD

**Issue by Laurendus** [BDSU/meeting-moderation-cards#4]
Wenn opening a room, it would be very convenient to display an automatically generated QR-Code which contains the Room-URL. 

With so many readily available QR-Code-Libraries I guess this should be fairly trivial and a quick win, but I sadly lack the experience to implement this reasonably fast.

If no one wants to implement this, I would have a go at it later some time.

**Comment by sarcaustech** [comment]
I like the idea! 

@acran Something for the WoC?
